### ISSUE TITLE
InvalidHandle exception thrown when canceling client action

### ISSUE THREAD

**Issue by clalancette** [ros2/rclpy#359]
## Bug report

I'm running the example rclpy minimal action server and action client_cancel, and the action client always throws an exception at the end.

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Source
- Version or commit hash:
  - 0.7.2
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

Terminal 1:
```
ros2 run examples_rclpy_minimal_action_server server_defer
```

Terminal 2:
```
ros2 run examples_rclpy_minimal_action_client client_cancel
```

#### Expected behavior
Client cancels the goal and exits cleanly.

#### Actual behavior
Client cancels the goal, but fails with:

```
[INFO] [minimal_action_client]: Waiting for action server...
[INFO] [minimal_action_client]: Sending goal request...
[INFO] [minimal_action_client]: Goal accepted :)
[INFO] [minimal_action_client]: Canceling goal
[INFO] [minimal_action_client]: Goal successfully canceled
Exception ignored in: <bound method ActionClient.__del__ of <rclpy.action.client.ActionClient object at 0x7fdcd40d4be0>>
Traceback (most recent call last):
  File "/home/ubuntu/ros2_ws/install/rclpy/lib/python3.6/site-packages/rclpy/action/client.py", line 577, in __del__
    self.destroy()
  File "/home/ubuntu/ros2_ws/install/rclpy/lib/python3.6/site-packages/rclpy/action/client.py", line 570, in destroy
    with self._node.handle as node_capsule:
  File "/home/ubuntu/ros2_ws/install/rclpy/lib/python3.6/site-packages/rclpy/handle.py", line 146, in __enter__
    return self._get_capsule()
  File "/home/ubuntu/ros2_ws/install/rclpy/lib/python3.6/site-packages/rclpy/handle.py", line 128, in _get_capsule
    raise InvalidHandle('Tried to use a handle that has been destroyed.')
rclpy.handle.InvalidHandle: Tried to use a handle that has been destroyed.
```

**Comment by jacobperron** [comment]
I'm also seeing this issue with the other action client example as well on macOS:

```
ros2 run examples_rclpy_minimal_action_client client
```
