### ISSUE TITLE
Failed to load entry point 'list': No module named 'rclpy._rclpy'

### ISSUE THREAD

**Issue by claireyywang** [ros2/rclpy#557]
## Bug report

**Required Info:**

- Operating System:
  - OSX Mojave
- Installation type:
  - binary from https://ci.ros2.org/view/packaging/job/packaging_osx/1844/
- Version or commit hash:
  - foxy beta
- DDS implementation:
  -Fast-rtps
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

```
ros2 node list
```

#### Expected behavior
output a list of nodes 

#### Actual behavior
```bash
/Users/clairewang/ros2_foxy/ros2-osx/bin/ros2
claire-remote:ros2_foxy clairewang$ ros2 node list
Failed to load entry point 'list': No module named 'rclpy._rclpy'
Traceback (most recent call last):
  File "/Users/clairewang/ros2_foxy/ros2-osx/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.9.2', 'console_scripts', 'ros2')()
  File "/Users/clairewang/ros2_foxy/ros2-osx/lib/python3.8/site-packages/ros2cli/cli.py", line 43, in main
    required=False, argv=argv)
  File "/Users/clairewang/ros2_foxy/ros2-osx/lib/python3.8/site-packages/ros2cli/command/__init__.py", line 250, in add_subparsers_on_demand
    command_parser, f'{cli_name} {name}', **kwargs)
  File "/Users/clairewang/ros2_foxy/ros2-osx/lib/python3.8/site-packages/ros2node/command/node.py", line 26, in add_arguments
    parser, cli_name, '_verb', 'ros2node.verb', required=False)
  File "/Users/clairewang/ros2_foxy/ros2-osx/lib/python3.8/site-packages/ros2cli/command/__init__.py", line 236, in add_subparsers_on_demand
    extension = command_extensions[name]
KeyError: 'list'
```

#### Additional information

Using `python 3.7`

**Comment by claireyywang** [comment]
gotta update to python@3.8. Doc updated by  https://github.com/ros2/ros2_documentation/pull/663
