### ISSUE TITLE
ros2 service call 'get_parameter_types' leads to coredump.

### ISSUE THREAD

**Issue by fujitatomoya** [ros2/rclpy#640]
## Bug report

- Operating System:
  - ubuntu20.04
- Installation type:
  - source build
- Version or commit hash:
  - https://github.com/ros2/ros2/commit/c059de9aadbf3d9ad189ca17d62f0110683c0a65
- DDS implementation:
  - Fast-DDS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

- service server

```
root@5c7a784cba7f:~/ros2_ws/colcon_ws# ros2 run demo_nodes_py talker
[INFO] [1606456496.047371800] [talker]: Publishing: "Hello World: 0"
[INFO] [1606456497.032341427] [talker]: Publishing: "Hello World: 1"
[INFO] [1606456498.032360895] [talker]: Publishing: "Hello World: 2"
Traceback (most recent call last):
  File "/root/ros2_ws/colcon_ws/install/demo_nodes_py/lib/demo_nodes_py/talker", line 11, in <module>
    load_entry_point('demo-nodes-py', 'console_scripts', 'talker')()
  File "/root/ros2_ws/colcon_ws/build/demo_nodes_py/demo_nodes_py/topics/talker.py", line 44, in main
    rclpy.spin(node)
  File "/root/ros2_ws/colcon_ws/install/rclpy/lib/python3.8/site-packages/rclpy/__init__.py", line 196, in spin
    executor.spin_once()
  File "/root/ros2_ws/colcon_ws/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 711, in spin_once
    raise handler.exception()
  File "/root/ros2_ws/colcon_ws/install/rclpy/lib/python3.8/site-packages/rclpy/task.py", line 239, in __call__
    self._handler.send(None)
  File "/root/ros2_ws/colcon_ws/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 426, in handler
    await call_coroutine(entity, arg)
  File "/root/ros2_ws/colcon_ws/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 380, in _execute_service
    response = await await_or_execute(srv.callback, request, srv.srv_type.Response())
  File "/root/ros2_ws/colcon_ws/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 118, in await_or_execute
    return callback(*args)
  File "/root/ros2_ws/colcon_ws/install/rclpy/lib/python3.8/site-packages/rclpy/parameter_service.py", line 89, in _get_parameter_types_callback
    response.types.append(param.type_)
TypeError: an integer is required (got type Type)
```

- service client

```
root@5c7a784cba7f:~/ros2_ws/colcon_ws# ros2 service call /talker/get_parameter_types rcl_interfaces/srv/GetParameterTypes "names: [use_sim_time, non_exist]"
waiting for service to become available...
requester: making request: rcl_interfaces.srv.GetParameterTypes_Request(names=['use_sim_time', 'non_exist'])
...<Ctrl-C to stop>
```

#### Expected behavior

Client can get type as followings w/o any coredump.

```
root@5c7a784cba7f:~/ros2_ws/colcon_ws# ros2 service call /talker/get_parameter_types rcl_interfaces/srv/GetParameterTypes "names: [use_sim_time]"
requester: making request: rcl_interfaces.srv.GetParameterTypes_Request(names=['use_sim_time'])

response:
rcl_interfaces.srv.GetParameterTypes_Response(types=[1])
```

#### Actual behavior

coredump

#### Additional information

rclcpp does not have this problem

**Comment by fujitatomoya** [comment]
It is obvious there is type error in,

https://github.com/ros2/rclpy/blob/ff56a94bcb3ae165b74cc1ade9ff34ae61ece81d/rclpy/rclpy/parameter_service.py#L88

I believe that `IntEnum` should be used here.
