### ISSUE TITLE
Throw exception ExternalShutdownException while receiving signal SIGTERM

### ISSUE THREAD

**Issue by Barry-Xu-2018** [ros2/rclpy#841]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - from source
- Version or commit hash:
  - master branch (6e3021b93b75f741d31060f4c12b50b65cf4ff97)
- DDS implementation:
  - default
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
1. execute example program
    ```
    ros2 run examples_rclpy_minimal_publisher publisher_member_function
    ```
2. Send signal `SIGTERM` to node itself.    

#### Expected behavior

No exception occurs.  
e.g.

[INFO] [1635316982.775247978] [minimal_publisher]: Publishing: 'Hello, world! 895'
[INFO] [1635316983.275271614] [minimal_publisher]: Publishing: 'Hello, world! 896'
[INFO] [1635316983.775252071] [minimal_publisher]: Publishing: 'Hello, world! 897'
[ros2run]: Terminated

#### Actual behavior

Exception is thrown.

```
Traceback (most recent call last):
  File "/home/barry-xu/Work/ROS2/ros2_latest_ws/install/examples_rclpy_minimal_publisher/lib/examples_rclpy_minimal_publisher/publisher_member_function", line 33, in <module>
    sys.exit(load_entry_point('examples-rclpy-minimal-publisher', 'console_scripts', 'publisher_member_function')())
  File "/home/barry-xu/Work/ROS2/ros2_latest_ws/build/examples_rclpy_minimal_publisher/examples_rclpy_minimal_publisher/publisher_member_function.py", line 43, in main
    rclpy.spin(minimal_publisher)
  File "/home/barry-xu/Work/ROS2/ros2_latest_ws/install/rclpy/lib/python3.8/site-packages/rclpy/__init__.py", line 219, in spin
    executor.spin_once()
  File "/home/barry-xu/Work/ROS2/ros2_latest_ws/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 704, in spin_once
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/home/barry-xu/Work/ROS2/ros2_latest_ws/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 690, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/home/barry-xu/Work/ROS2/ros2_latest_ws/install/rclpy/lib/python3.8/site-packages/rclpy/executors.py", line 592, in _wait_for_ready_callbacks
    raise ExternalShutdownException()
rclpy.executors.ExternalShutdownException
[ros2run]: Process exited with failure 1
```

**Comment by ivanpauno** [comment]
This is an expected change after https://github.com/ros2/rclpy/pull/830.
You need to catch the exception.

See also https://github.com/ros2/rclpy/pull/844 and https://github.com/ros2/demos/pull/539.

**Comment by Barry-Xu-2018** [comment]
> This is an expected change after #830.
> You need to catch the exception.
>
> See also #844 and ros2/demos#539.

Get it. Thank you.

**Comment by Barry-Xu-2018** [comment]
According to current design, user should handle exception `ExternalShutdownException`.  
So this isn't a bug.  
I close this issue.
