### ISSUE TITLE
ParameterAlreadyDeclaredException during instantiation of Node with automatically_declare_parameters_from_overrides

### ISSUE THREAD

**Issue by xouillet** [ros2/rclpy#948]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - Binary
- Version or commit hash:
  - 1.9.1
- DDS implementation:
  - CycloneDDS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

With release 1.9.1, when instancing Node with `automatically_declare_parameters_from_overrides`, we can experience a `ParameterAlreadyDeclaredException` if a launch parameter from the mother class is one of the core parameter of Node (`use_sim_time` for example).

`joint_state_publisher` is affected by this bug in last `galactic` ubuntu package, this can be easily tested with

```
$ ros2 run joint_state_publisher joint_state_publisher --ros-args -p use_sim_time:=True
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/joint_state_publisher/joint_state_publisher", line 11, in <module>
    load_entry_point('joint-state-publisher==2.2.0', 'console_scripts', 'joint_state_publisher')()
  File "/opt/ros/galactic/lib/python3.8/site-packages/joint_state_publisher/joint_state_publisher.py", line 415, in main
    jsp = JointStatePublisher(parsed_args.urdf_file)
  File "/opt/ros/galactic/lib/python3.8/site-packages/joint_state_publisher/joint_state_publisher.py", line 217, in __init__
    super().__init__('joint_state_publisher', automatically_declare_parameters_from_overrides=True)
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/node.py", line 216, in __init__
    self.declare_parameters(
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/node.py", line 487, in declare_parameters
    raise ParameterAlreadyDeclaredException(parameters_already_declared)
rclpy.exceptions.ParameterAlreadyDeclaredException: ('Parameter(s) already declared', ['use_sim_time'])
```

Minimal snippet to reproduce:

bug.py:
```
import rclpy.node

class NewNode(rclpy.node.Node):
    def __init__(self):
        super().__init__('newnode', automatically_declare_parameters_from_overrides=True)

rclpy.init()
rclpy.spin(NewNode())
rclpy.shutdown()
```
```
$ python3 bug.py --ros-args -p use_sim_time:=True
Traceback (most recent call last):
  File "bug.py", line 8, in <module>
    rclpy.spin(NewNode())
  File "bug.py", line 5, in __init__
    super().__init__('newnode', automatically_declare_parameters_from_overrides=True)
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/node.py", line 216, in __init__
    self.declare_parameters(
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/node.py", line 487, in declare_parameters
    raise ParameterAlreadyDeclaredException(parameters_already_declared)
rclpy.exceptions.ParameterAlreadyDeclaredException: ('Parameter(s) already declared', ['use_sim_time'])
```

#### Expected behavior

No exception should be raised.

This was the behavior in 1.9.0 and https://docs.ros2.org/galactic/api/rclcpp/classrclcpp_1_1NodeOptions.html#a094ceb7af7c9b358ec007a4b8e14d40d

#### Actual behavior

```
rclpy.exceptions.ParameterAlreadyDeclaredException: ('Parameter(s) already declared', ['use_sim_time'])
```

#### Additional information

This was introduced by the commit https://github.com/ros2/rclpy/commit/4d97b4ecf0ae5ae42a4ed7e41cffcacb51a85219.
`ParameterAlreadyDeclaredException` should be catched when calling `declare_parameters`. I will provide a pull request with this fix.

**Comment by xouillet** [comment]
Duplicate of #942, closing
