### ISSUE TITLE
Program is frozen on spin_once()

### ISSUE THREAD

**Issue by KiBots** [ros2/rclpy#965]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries 
- Client library (if applicable):
  - rclpy 

#### Steps to reproduce issue

```


```

#### Expected behavior
Program should publish velocity
#### Actual behavior
Program frozen
#### Additional information
After ctrl + c I can see this:
```
^CTraceback (most recent call last):
  File "gaz.py", line 140, in <module>
    lis_odom()
  File "gaz.py", line 135, in lis_odom
    rclpy.spin_once(sign_sub, timeout_sec=0)
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/__init__.py", line 176, in spin_once
    executor.spin_once(timeout_sec=timeout_sec)
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/executors.py", line 704, in spin_once
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/executors.py", line 690, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/executors.py", line 550, in _wait_for_ready_callbacks
    context_stack.enter_context(gc.handle)
  File "/usr/lib/python3.8/contextlib.py", line 426, in enter_context
    self._push_cm_exit(cm, _exit)
  File "/usr/lib/python3.8/contextlib.py", line 461, in _push_cm_exit
    self._push_exit_callback(_exit_wrapper, True)
KeyboardInterrupt
```

**Comment by KiBots** [comment]
Sorry guys. That was a stupid mistake of not knowing my friend's program. All good.
